//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wollen Sie anonym spenden und verlassen den goodie? (kein Login-Konto erforderlich).
        /// </summary>
        internal static string abondon {
            get {
                return ResourceManager.GetString("abondon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kundenkonto Login.
        /// </summary>
        internal static string Account_Login {
            get {
                return ResourceManager.GetString("Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add goodie.
        /// </summary>
        internal static string Add_goodie {
            get {
                return ResourceManager.GetString("Add_goodie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fügen Sie einen neuen goodie.
        /// </summary>
        internal static string Add_new_goodie {
            get {
                return ResourceManager.GetString("Add_new_goodie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        internal static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login your email to active the new account.
        /// </summary>
        internal static string Alter_activeaccount {
            get {
                return ResourceManager.GetString("Alter_activeaccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please login your email to check the password.
        /// </summary>
        internal static string Alter_checkpwd {
            get {
                return ResourceManager.GetString("Alter_checkpwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emaill Address or Passowrd is wrong.
        /// </summary>
        internal static string Alter_emailwrong {
            get {
                return ResourceManager.GetString("Alter_emailwrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Success, We will feedback as soon as possible.
        /// </summary>
        internal static string Alter_feedback {
            get {
                return ResourceManager.GetString("Alter_feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Success,You can go login now!.
        /// </summary>
        internal static string Alter_gologin {
            get {
                return ResourceManager.GetString("Alter_gologin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is wrong.
        /// </summary>
        internal static string Alter_Pwdwrong {
            get {
                return ResourceManager.GetString("Alter_Pwdwrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to regist failed.
        /// </summary>
        internal static string Alter_registfailed {
            get {
                return ResourceManager.GetString("Alter_registfailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server cancled email,Please try again after!.
        /// </summary>
        internal static string Alter_servercancled {
            get {
                return ResourceManager.GetString("Alter_servercancled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error,Please try again!.
        /// </summary>
        internal static string Alter_tryagain {
            get {
                return ResourceManager.GetString("Alter_tryagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to und stimmen?.
        /// </summary>
        internal static string And_Agree {
            get {
                return ResourceManager.GetString("And_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where are you from?.
        /// </summary>
        internal static string Are_you_from {
            get {
                return ResourceManager.GetString("Are_you_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geburtstag.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekte von Sport.
        /// </summary>
        internal static string BySport {
            get {
                return ResourceManager.GetString("BySport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie einen Kanton.
        /// </summary>
        internal static string Canton {
            get {
                return ResourceManager.GetString("Canton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennwort ändern.
        /// </summary>
        internal static string Change_pwd {
            get {
                return ResourceManager.GetString("Change_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Summary (140 Zeichen max).
        /// </summary>
        internal static string Char_Max {
            get {
                return ResourceManager.GetString("Char_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt.
        /// </summary>
        internal static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 111 Tage.
        /// </summary>
        internal static string Days_111 {
            get {
                return ResourceManager.GetString("Days_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 33 Tage.
        /// </summary>
        internal static string Days_33 {
            get {
                return ResourceManager.GetString("Days_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 333 Tage.
        /// </summary>
        internal static string Days_333 {
            get {
                return ResourceManager.GetString("Days_333", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 77 Tage.
        /// </summary>
        internal static string Days_77 {
            get {
                return ResourceManager.GetString("Days_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 99 Tage.
        /// </summary>
        internal static string Days_99 {
            get {
                return ResourceManager.GetString("Days_99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung deines Goodies:.
        /// </summary>
        internal static string Desc_goodie {
            get {
                return ResourceManager.GetString("Desc_goodie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spenden.
        /// </summary>
        internal static string Donate {
            get {
                return ResourceManager.GetString("Donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spenden Formular.
        /// </summary>
        internal static string Donate_Form {
            get {
                return ResourceManager.GetString("Donate_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was brauchen Sie?.
        /// </summary>
        internal static string Do_You_Need {
            get {
                return ResourceManager.GetString("Do_You_Need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mein Konto bearbeiten.
        /// </summary>
        internal static string Edit_Account {
            get {
                return ResourceManager.GetString("Edit_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bald endende.
        /// </summary>
        internal static string Ending_Soonest {
            get {
                return ResourceManager.GetString("Ending_Soonest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Facebook-Seite?.
        /// </summary>
        internal static string FaceBookPage {
            get {
                return ResourceManager.GetString("FaceBookPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weiblich.
        /// </summary>
        internal static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragebogen, Felder mit.
        /// </summary>
        internal static string FieldsWith {
            get {
                return ResourceManager.GetString("FieldsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        internal static string First_name {
            get {
                return ResourceManager.GetString("First_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to we will send the password to your mailbox.
        /// </summary>
        internal static string ForgetPwd {
            get {
                return ResourceManager.GetString("ForgetPwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gründer-Log.
        /// </summary>
        internal static string Founder_log {
            get {
                return ResourceManager.GetString("Founder_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gefunden ein Projekt in 2 Steps.
        /// </summary>
        internal static string FoundProject {
            get {
                return ResourceManager.GetString("FoundProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Informationen.
        /// </summary>
        internal static string Fun_info {
            get {
                return ResourceManager.GetString("Fun_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gründer Informationen.
        /// </summary>
        internal static string F_Info {
            get {
                return ResourceManager.GetString("F_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gründer Namen.
        /// </summary>
        internal static string F_name {
            get {
                return ResourceManager.GetString("F_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geschlecht.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemeine Informationen.
        /// </summary>
        internal static string Genernal_info {
            get {
                return ResourceManager.GetString("Genernal_info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sie eine E-Mail mit einem Link zu Ihrer E-Mail-Adresse bestätigen.
        /// </summary>
        internal static string GetEmail {
            get {
                return ResourceManager.GetString("GetEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hat für dieses Projekt gespendet, DANKE!.
        /// </summary>
        internal static string had_donated {
            get {
                return ResourceManager.GetString("had_donated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Haben Sie die.
        /// </summary>
        internal static string Have_You_Read {
            get {
                return ResourceManager.GetString("Have_You_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hilfe.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie lange die Spende dauern wird?.
        /// </summary>
        internal static string How_Long {
            get {
                return ResourceManager.GetString("How_Long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie viel die Spende zu sammeln?.
        /// </summary>
        internal static string How_Much {
            get {
                return ResourceManager.GetString("How_Much", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie viel der Spender spenden, um es zu bekommen:.
        /// </summary>
        internal static string How_much_donate {
            get {
                return ResourceManager.GetString("How_much_donate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie es funktioniert.
        /// </summary>
        internal static string Index_How_Work {
            get {
                return ResourceManager.GetString("Index_How_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen?.
        /// </summary>
        internal static string Index_Login_Forgot {
            get {
                return ResourceManager.GetString("Index_Login_Forgot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Konto.
        /// </summary>
        internal static string Index_Login_MyAccount {
            get {
                return ResourceManager.GetString("Index_Login_MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angemeldet bleiben.
        /// </summary>
        internal static string Index_Login_Remember {
            get {
                return ResourceManager.GetString("Index_Login_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen Sie ein Projekt !.
        /// </summary>
        internal static string Index_Project_Create {
            get {
                return ResourceManager.GetString("Index_Project_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gehen und gehen.
        /// </summary>
        internal static string Index_Project_Go {
            get {
                return ResourceManager.GetString("Index_Project_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verfügbare Extras.
        /// </summary>
        internal static string Index_Project_Goody {
            get {
                return ResourceManager.GetString("Index_Project_Goody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta neque sequi ducimus perspiciatis impedit voluptatem sapiente magnam id aperiam nemo. Itaque ad aspernatur tempore voluptatem modi omnis deleniti mollitia minus..
        /// </summary>
        internal static string Index_Project_Summary {
            get {
                return ResourceManager.GetString("Index_Project_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekte des Tages.
        /// </summary>
        internal static string Index_Project_Title {
            get {
                return ResourceManager.GetString("Index_Project_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Your Local-Team.
        /// </summary>
        internal static string Index_Top_Title {
            get {
                return ResourceManager.GetString("Index_Top_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finde es heraus.
        /// </summary>
        internal static string Index_What_Figure {
            get {
                return ResourceManager.GetString("Index_What_Figure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipisicing elit. Soluta neque sequi ducimus perspiciatis impedit voluptatem sapiente magnam id aperiam nemo..
        /// </summary>
        internal static string Index_What_Summary {
            get {
                return ResourceManager.GetString("Index_What_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was ist der Support Your Local Team?.
        /// </summary>
        internal static string Index_What_Title {
            get {
                return ResourceManager.GetString("Index_What_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wer bist du?.
        /// </summary>
        internal static string Introduce {
            get {
                return ResourceManager.GetString("Introduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        internal static string Last_name {
            get {
                return ResourceManager.GetString("Last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lage.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einloggen out.
        /// </summary>
        internal static string Loginout {
            get {
                return ResourceManager.GetString("Loginout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie die unten stehenden Formulare.
        /// </summary>
        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to männlich.
        /// </summary>
        internal static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neueste.
        /// </summary>
        internal static string Most_Recent {
            get {
                return ResourceManager.GetString("Most_Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie viel möchten Sie geben?.
        /// </summary>
        internal static string much_give {
            get {
                return ResourceManager.GetString("much_give", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Gespendet Projekte.
        /// </summary>
        internal static string MyDonatedProc {
            get {
                return ResourceManager.GetString("MyDonatedProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my order.
        /// </summary>
        internal static string Myorder {
            get {
                return ResourceManager.GetString("Myorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Geförderte Projekte.
        /// </summary>
        internal static string MyProc {
            get {
                return ResourceManager.GetString("MyProc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mein Profil.
        /// </summary>
        internal static string myprofile {
            get {
                return ResourceManager.GetString("myprofile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihr Konto.
        /// </summary>
        internal static string My_Account {
            get {
                return ResourceManager.GetString("My_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of your goodie:.
        /// </summary>
        internal static string Name_goodie {
            get {
                return ResourceManager.GetString("Name_goodie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name des Projekts?.
        /// </summary>
        internal static string Name_Of_Project {
            get {
                return ResourceManager.GetString("Name_Of_Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warum brauchen Sie das?.
        /// </summary>
        internal static string Need_Reason {
            get {
                return ResourceManager.GetString("Need_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erstellen Sie ein neues Konto.
        /// </summary>
        internal static string NewAccount {
            get {
                return ResourceManager.GetString("NewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, bitte senden Sie mir Newsletter..
        /// </summary>
        internal static string NewsLetter {
            get {
                return ResourceManager.GetString("NewsLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schön, dass Sie hier zu sehen!.
        /// </summary>
        internal static string NiceSee {
            get {
                return ResourceManager.GetString("NiceSee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nicht.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anzahl der Goodies Sie präsentieren:.
        /// </summary>
        internal static string Number_goodie {
            get {
                return ResourceManager.GetString("Number_goodie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altes Passwort.
        /// </summary>
        internal static string Old_pwd {
            get {
                return ResourceManager.GetString("Old_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kennwort.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte füllen Sie die Formulare aus, um eine E-Mail an uns zu senden..
        /// </summary>
        internal static string Please_SendEmail {
            get {
                return ResourceManager.GetString("Please_SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privatleben.
        /// </summary>
        internal static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fortschritt.
        /// </summary>
        internal static string Progress {
            get {
                return ResourceManager.GetString("Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekt Kategorie.
        /// </summary>
        internal static string ProjectCategory {
            get {
                return ResourceManager.GetString("ProjectCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projektbeschreibung.
        /// </summary>
        internal static string pro_desc {
            get {
                return ResourceManager.GetString("pro_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fragebogen.
        /// </summary>
        internal static string Questionnaire {
            get {
                return ResourceManager.GetString("Questionnaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regist.
        /// </summary>
        internal static string Regist {
            get {
                return ResourceManager.GetString("Regist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to übrig.
        /// </summary>
        internal static string Remain_Goal {
            get {
                return ResourceManager.GetString("Remain_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort wiederholen.
        /// </summary>
        internal static string RepPassword {
            get {
                return ResourceManager.GetString("RepPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alle erforderlichen.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressourcen.
        /// </summary>
        internal static string Resources {
            get {
                return ResourceManager.GetString("Resources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ergebnisse für den Suchbegriff.
        /// </summary>
        internal static string Result_Term {
            get {
                return ResourceManager.GetString("Result_Term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche Projekt.
        /// </summary>
        internal static string SearchProject {
            get {
                return ResourceManager.GetString("SearchProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projekte, die von Region.
        /// </summary>
        internal static string Search_Country_Title {
            get {
                return ResourceManager.GetString("Search_Country_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        internal static string Search_Top_Title {
            get {
                return ResourceManager.GetString("Search_Top_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to suchte in Projekte.
        /// </summary>
        internal static string search_with_project {
            get {
                return ResourceManager.GetString("search_with_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie einen Kanton.
        /// </summary>
        internal static string Select_Canton {
            get {
                return ResourceManager.GetString("Select_Canton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kategorie auswählen.
        /// </summary>
        internal static string Select_Category {
            get {
                return ResourceManager.GetString("Select_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wählen Sie Ihr Land.
        /// </summary>
        internal static string Select_Country {
            get {
                return ResourceManager.GetString("Select_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sortieren nach:.
        /// </summary>
        internal static string Sortby {
            get {
                return ResourceManager.GetString("Sortby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thema.
        /// </summary>
        internal static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to einreichen.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anhänger.
        /// </summary>
        internal static string supporters {
            get {
                return ResourceManager.GetString("supporters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzungsbedingungen.
        /// </summary>
        internal static string Terms_Of_Service {
            get {
                return ResourceManager.GetString("Terms_Of_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nutzungsbedingungen.
        /// </summary>
        internal static string Terms_service {
            get {
                return ResourceManager.GetString("Terms_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdient.
        /// </summary>
        internal static string Total_Date {
            get {
                return ResourceManager.GetString("Total_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tor.
        /// </summary>
        internal static string Total_Goal {
            get {
                return ResourceManager.GetString("Total_Goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stadt.
        /// </summary>
        internal static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unbegrenzt.
        /// </summary>
        internal static string Unlimited {
            get {
                return ResourceManager.GetString("Unlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hochladen eines Bildes für Ihr Projekt.
        /// </summary>
        internal static string Upload_Image {
            get {
                return ResourceManager.GetString("Upload_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzeranmeldung.
        /// </summary>
        internal static string Userlogin {
            get {
                return ResourceManager.GetString("Userlogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to via Treuhandkonto.
        /// </summary>
        internal static string VIA {
            get {
                return ResourceManager.GetString("VIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was ist Ihre Vision?.
        /// </summary>
        internal static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich möchte dieses goodie.
        /// </summary>
        internal static string want_goodie {
            get {
                return ResourceManager.GetString("want_goodie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ihre Webseite?.
        /// </summary>
        internal static string WebPage {
            get {
                return ResourceManager.GetString("WebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to willkommen.
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was brauchen.
        /// </summary>
        internal static string What_need {
            get {
                return ResourceManager.GetString("What_need", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Was ist unsere Vision?.
        /// </summary>
        internal static string What_our_vision {
            get {
                return ResourceManager.GetString("What_our_vision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welche Methode bevorzugen Sie?.
        /// </summary>
        internal static string Which_method {
            get {
                return ResourceManager.GetString("Which_method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wer sind wir?.
        /// </summary>
        internal static string Who_are_we {
            get {
                return ResourceManager.GetString("Who_are_we", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warum brauchen wir das?.
        /// </summary>
        internal static string Why_do_we {
            get {
                return ResourceManager.GetString("Why_do_we", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ja.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Youtube-Link.
        /// </summary>
        internal static string YoutubeLink {
            get {
                return ResourceManager.GetString("YoutubeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP.
        /// </summary>
        internal static string ZIP {
            get {
                return ResourceManager.GetString("ZIP", resourceCulture);
            }
        }
    }
}
