//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace MEDIA.Model
{
    public partial class Entities : ObjectContext
    {
        public const string ConnectionString = "name=Entities";
        public const string ContainerName = "Entities";
    
        #region Constructors
    
        public Entities()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<Administrator> Administrators
        {
            get { return _administrators  ?? (_administrators = CreateObjectSet<Administrator>("Administrators")); }
        }
        private ObjectSet<Administrator> _administrators;
    
        public ObjectSet<DonateRecord> DonateRecords
        {
            get { return _donateRecords  ?? (_donateRecords = CreateObjectSet<DonateRecord>("DonateRecords")); }
        }
        private ObjectSet<DonateRecord> _donateRecords;
    
        public ObjectSet<DonationProject> DonationProjects
        {
            get { return _donationProjects  ?? (_donationProjects = CreateObjectSet<DonationProject>("DonationProjects")); }
        }
        private ObjectSet<DonationProject> _donationProjects;
    
        public ObjectSet<Goody> Goodies
        {
            get { return _goodies  ?? (_goodies = CreateObjectSet<Goody>("Goodies")); }
        }
        private ObjectSet<Goody> _goodies;
    
        public ObjectSet<OrderDetail> OrderDetails
        {
            get { return _orderDetails  ?? (_orderDetails = CreateObjectSet<OrderDetail>("OrderDetails")); }
        }
        private ObjectSet<OrderDetail> _orderDetails;
    
        public ObjectSet<OrderInfo> OrderInfoes
        {
            get { return _orderInfoes  ?? (_orderInfoes = CreateObjectSet<OrderInfo>("OrderInfoes")); }
        }
        private ObjectSet<OrderInfo> _orderInfoes;
    
        public ObjectSet<Product> Products
        {
            get { return _products  ?? (_products = CreateObjectSet<Product>("Products")); }
        }
        private ObjectSet<Product> _products;
    
        public ObjectSet<ProductClass> ProductClasses
        {
            get { return _productClasses  ?? (_productClasses = CreateObjectSet<ProductClass>("ProductClasses")); }
        }
        private ObjectSet<ProductClass> _productClasses;
    
        public ObjectSet<ProductInventory> ProductInventories
        {
            get { return _productInventories  ?? (_productInventories = CreateObjectSet<ProductInventory>("ProductInventories")); }
        }
        private ObjectSet<ProductInventory> _productInventories;
    
        public ObjectSet<Questionnaire> Questionnaires
        {
            get { return _questionnaires  ?? (_questionnaires = CreateObjectSet<Questionnaire>("Questionnaires")); }
        }
        private ObjectSet<Questionnaire> _questionnaires;
    
        public ObjectSet<ShopCar> ShopCars
        {
            get { return _shopCars  ?? (_shopCars = CreateObjectSet<ShopCar>("ShopCars")); }
        }
        private ObjectSet<ShopCar> _shopCars;
    
        public ObjectSet<User> Users
        {
            get { return _users  ?? (_users = CreateObjectSet<User>("Users")); }
        }
        private ObjectSet<User> _users;
    
        public ObjectSet<UserAnswer> UserAnswers
        {
            get { return _userAnswers  ?? (_userAnswers = CreateObjectSet<UserAnswer>("UserAnswers")); }
        }
        private ObjectSet<UserAnswer> _userAnswers;

        #endregion
    }
}
